import * as React from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';


const AutoComplete = () => {


  return (
    <Autocomplete
        value={value}
        onChange={(event, newValue) => {
          setValue(newValue);
        }}
        inputValue={inputValue}
        onInputChange={(event, newInputValue) => {
        setInputValue(newInputValue);
        }}
        id="controllable-states-demo"
        options={options}
        sx={{ width: 300 }}
        renderInput={(params) => 
        <TextField {...params} label="Foods" 
        variant="outlined"
        type="text"
        InputLabelProps={{
            sx: { color: 'white' },
        }}
        sx={{
            '& .MuiOutlinedInput-root': {
            '& fieldset': {
                borderColor: '#90caf9',
            },
            '&:hover fieldset': {
                borderColor: '#90caf9',
            },
            '&.Mui-focused fieldset': {
                borderColor: '#90caf9',
            },
            },
        }}
        />}
    />
  );
};


const Foods = [
  { label: 'Back to Nature (Mondelez International)' },
  { label: 'Bimbo' },
  { label: 'Daves Killer Bread' },
  { label: 'Entenmanns' },
  { label: 'Kings Hawaiian' },
  { label: 'Lenders Bagels' },
  { label: 'Natures Own' },
  { label: 'Pepperidge Farm' },
  { label: 'Tastykake' },
  { label: 'Thomas' },
  { label: 'Wonder Bread' },
  { label: 'Betty Crocker' },
  { label: 'Bisquick' },
  { label: 'Bobs Red Mill' },
  { label: 'Cake' },
  { label: 'Cookie' },
  { label: 'Cheesecake' },
  { label: 'Carrot cake' },
  { label: 'Strawberry cake' },
  { label: 'Ice-cream cake' },
  { label: 'Vanilla cake' },
  { label: 'Red velvet cake' },
  { label: 'Cupcake' },
  { label: 'Fudge cake' },
  { label: 'Chocolate' },
  { label: 'Mozzarella' },
  { label: 'Brie' },
  { label: 'Feta' },
  { label: 'Blue cheese' },
  { label: 'Parmesan' },
  { label: 'Cheese stick' },
  { label: 'Cheesestrings' },
  { label: 'Donuts' },
  { label: 'Jam' },
  { label: 'Sprinkles' },
  { label: 'Krispy Kreme' },
  { label: 'Arepa' },
  { label: 'Pierogi' },
  { label: 'Wonton' },
  { label: 'Apple' },
  { label: 'Banana' },
  { label: 'Cantaloupe' },
  { label: 'Durian' },
  { label: 'Orange' },
  { label: 'Cherry' },
  { label: 'Kiwi' },
  { label: 'Watermelon' },
  { label: 'Avocado' },
  { label: 'Apricot' },
  { label: 'Pear' },
  { label: 'Pineapple' },
  { label: 'Strawberry' },
  { label: 'Blueberry' },
  { label: 'Raspberry' },
  { label: 'French fries' },
  { label: 'Cereal' },
  { label: 'Corn' },
  { label: 'Popcorn' },
  { label: 'Rice' },
  { label: 'Ice cream' },
  { label: 'Chocolate ice cream' },
  { label: 'Vanilla ice cream' },
  { label: 'Cookies and cream' },
  { label: 'Mint chocolate' },
  { label: 'Rocky Road' },
  { label: 'Pistachio' },
  { label: 'Strawberry ice cream' },
  { label: 'Superman ice cream' },
  { label: 'Neapolitan' },
  { label: 'Mashed potatoes' },
  { label: 'Beef' },
  { label: 'Wagyu' },
  { label: 'Steak' },
  { label: 'Pork' },
  { label: 'Bacon' },
  { label: 'Ham' },
  { label: 'Buffalo wing' },
  { label: 'Chicken nuggets' },
  { label: 'Chicken steak' },
  { label: 'Roast chicken' },
  { label: 'Ribs' },
  { label: 'Fish' },
  { label: 'Salmon' },
  { label: 'Shrimp' },
  { label: 'Shark' },
  { label: 'Scrambled egg' },
  { label: 'Sunny side up' },
  { label: 'Omelette' },
  { label: 'Boiled egg' },
  { label: 'Tea egg' },
  { label: 'Century egg' },
  { label: 'Almond milk' },
  { label: 'Soy milk' },
  { label: 'Cow milk' },
  { label: 'Goat milk' },
  { label: 'Onion rings' },
  { label: 'Lasagna' },
  { label: 'Linguini' },
  { label: 'Ravioli' },
  { label: 'Carbonara' },
  { label: 'Bolognese' },
  { label: 'Spaghetti' },
  { label: 'Spaghetti and meatballs' },
  { label: 'Pancit canton' },
  { label: 'Fettuccine' },
  { label: 'Pudding' },
  { label: 'Pupusa' },
  { label: 'Shepherds pie' },
  { label: 'Apple pie' },
  { label: 'Cream pie' },
  { label: 'Pumpkin pie' },
  { label: 'Key lime pie' },
  { label: 'Peach pie' },
  { label: 'Pizza' },
  { label: 'Pepperoni pizza' },
  { label: 'Hawaiian pizza' },
  { label: 'Margherita pizza' },
  { label: 'Croquette' },
  { label: 'Egg roll' },
  { label: 'Spring roll' },
  { label: 'Lumpia' },
  { label: 'Vegetable sandwich' },
  { label: 'Grilled Cheese' },
  { label: 'Panini' },
  { label: 'Cheeseburgers' },
  { label: 'Bacon cheeseburger' },
  { label: 'Hamburgers' },
  { label: 'Chicken burger' },
  { label: 'Hot dogs' },
  { label: 'Peanut butter and jam sandwich' },
  { label: 'Submarine sandwich' },
  { label: 'Chowder' },
  { label: 'Clam Chowder' },
  { label: 'Corn chowder' },
  { label: 'Sinigang' },
  { label: 'Sushi' },
  { label: 'Stew' },
  { label: 'Taco' },
  { label: 'Tamale' },
  { label: 'Turnover' },
  { label: 'Jamaican patty' },
  { label: 'Waffle' },
  { label: 'Roti Canai' },
  { label: 'Back to Nature' },
  { label: 'Aunt Jemima' },
  { label: 'Pillsbury' },
  { label: 'Ralcorp' },
  { label: 'Streits' },
  { label: 'Danone' },
  { label: 'Capri-Sun' },
  { label: 'Nestle' },
  { label: 'Nestea' },
  { label: 'Ovaltine' },
  { label: 'Silk' },
  { label: 'Swiss Miss' },
  { label: 'Welchs' },
  { label: 'Arnott' },
  { label: 'Chips Ahoy' },
  { label: 'Foxs Biscuits' },
  { label: 'McVities' },
  { label: 'Oreo' },
  { label: 'Pepperidge Farm' },
  { label: 'Ritz' },
  { label: 'Triscuit' },
  { label: 'Balance Bar' },
  { label: 'Clif Bar' },
  { label: 'PowerBar' },
  { label: 'Cream of Wheat' },
  { label: 'Quaker Oats Company' },
  { label: 'Twinkie' },
  { label: 'Gerber' },
  { label: 'Green Giant' },
  { label: 'Heinz' },
  { label: 'Hormel' },
  { label: 'Jennie-O' },
  { label: 'Oscar Mayer' },
  { label: 'Becel' },
  { label: 'Bertolli' },
  { label: 'Blue Bonnet' },
  { label: 'Country Crock' },
  { label: 'Flora' },
  { label: 'I Cant Believe Its Not Butter' },
  { label: 'Land O Lakes' },
  { label: 'Pam' },
  { label: 'Vlasic Pickles' },
  { label: 'DiGiorno' },
  { label: 'Lean Cuisine' },
  { label: 'Swanson' },
  { label: 'Weight Watchers' },
  { label: 'Yoplait' },
  { label: 'Knorr' },
  { label: 'Maggi' },
  { label: 'Jif' },
  { label: 'Nutella' },
  { label: 'Skippy' },
  { label: 'Twix' },
];

  

export default AutoComplete;